Ref/reorder readme
edgelesssys/graphene-tensorflow-demo pull request #4
Opened 2021-05-20 14:00 UTC by daniel-weisse

2021-05-23 14:18 UTC, thomasten requested changes

2021-05-23 14:18 UTC, thomasten commented on README.md
> +However you may also build your own by following the steps [of this tutorial](#Building-the-Docker-Image).
```suggestion
You can also [build it yourself](#Building-the-Docker-Image).
```
short sentences

2021-05-23 14:18 UTC, thomasten commented on README.md
> +Note that, if you plan to build your own image, you will have to change the image name in `kubernetes/templates/tf-server.yaml`.
maybe move the sentence about renaming into the corresponding section?

2021-05-23 14:18 UTC, thomasten commented on README.md
> +You can run the demo with Marblerun as a standalone by following these steps.
```suggestion
### Standalone

You can run the demo with Marblerun in standalone mode as follows:
```

2021-05-23 14:18 UTC, thomasten commented on README.md
> +    This will pull our docker image. If you wish to use your own change `image_id` in `tools/run_tf_image.sh` to the name of your image.
parameterize the script instead?

2021-05-25 08:49 UTC, m1ghtym0 approved these changes

2021-05-25 08:50 UTC, thomasten approved these changes

2021-05-25 08:52 UTC, merged